name: main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - name: Create ZIP package
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: dist/*
